config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"

  
  resources :locations do
    resources :characters
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/character.rb
class Character < ApplicationRecord
    belongs_to :location
end

app/models/location.rb
class Location < ApplicationRecord
    has_many :characters
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/characters_controller.rb
class CharactersController < ApplicationController
    def index
        
    end
end

app/controllers/locations_controller.rb
class LocationsController < ApplicationController
    def index
        @locations = Location.all
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/characters_helper.rb
module CharactersHelper
end

app/helpers/locations_helper.rb
module LocationsHelper
end

app/views/characters/index.html.erb
<h1>Characters Index Page</h1>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsReviewApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/locations/index.html.erb
<h1>Locations Index Page</h1>

<ul>
    <% @locations.each do |location| %>
        <li>
            <%= link_to location.name, location_characters_path(location) %>
        </li>
    <% end %>
</ul>